# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Peter Simon
tagline:          'IT Consulting'
description:      'Skalierbare und hochverfügbare Web-Infrastrukturen, auf Basis von Open Source Technologien.'
url:              http://www.simon-it-consulting.de
baseurl:          /

author:
  name:           'Peter Simon'
  url:            https://twitter.com/no_tomato_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
